name: 🔨 Build Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.22.x,1.21.x,1.20.x,1.19.x,1.18.x,1.17.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test
        run: go test -race -cover ./...

      - name: Race Condition Tests
        if: ${{ matrix.os != 'windows-latest' }} # false positives in windows
        run: go test -race ./...

      - name: Fuzz File Read  # fuzz tests need to be run separately  
        run:  go test -fuzztime=10s -fuzz=FuzzSafeOpen -run "FuzzSafeOpen" ./file/...
